name: CI/CD Pipeline
on: 
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Install dependencies
        run: npm install

      - name: Run Unit test if any added
        run: |
          found="F"
          for changed_file in ${{ steps.files.outputs.all }}; do
            if echo "${changed_file}" | grep -q "\.test\.js$"; then
                found="T"
            fi
          done
          if [ "$found" = "T" ]; then
            echo "Unit Test File Added, running integration testing"
          else
            echo "No Unit Test file added, yet running integration testing"
          fi
          cd jellybean_fortune; npm i; npm test

      - name: Lint code
        run: cd jellybean_fortune; npm i; npm run lint
        run: git status
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

      - name: Generate documentation
        run: cd jellybean_fortune; npm i; npm run docs
      
