name: CI/CD Pipeline
on:
  pull_request:
    branches: main

permissions:
  contents: write
  pull-requests: write

jobs:

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Install dependencies
        run: cd jellybean_fortune; npm install

      - name: Run Unit test if any added
        run: |
          found="F"
          for changed_file in ${{ steps.files.outputs.all }}; do
            if echo "${changed_file}" | grep -q "\.test\.js$"; then
                found="T"
            fi
          done
          if [ "$found" = "T" ]; then
            echo "Unit Test File Added, running integration testing"
          else
            echo "No Unit Test file added, yet running integration testing"
          fi
          cd jellybean_fortune; npm i; npm test

  Prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,md,html,css}
          same_commit: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # Linter:
  #   needs: [Test, Prettier]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Super-Linter
  #       uses: super-linter/super-linter@v5.0.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         VALIDATE_ALL_CODEBASE: true
  #         VALIDATE_CSS: true
  #         VALIDATE_HTML: true
  #         VALIDATE_JAVASCRIPT_ES: true

  docs:
    needs: [Test, Prettier]
    name: Documentation Generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: JS DOCS generation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./jellybean_fortune
          recurse: true
          output_dir: ./out